// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArE-oAEdxp_7eTAY5F5kiCnSBSDUuBTzQ',
    appId: '1:376786311168:web:7b377f7806764a1e5420e5',
    messagingSenderId: '376786311168',
    projectId: 'tutleneck25',
    authDomain: 'tutleneck25.firebaseapp.com',
    storageBucket: 'tutleneck25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChl15BO5GMh8dFO2YYL_S366HafnMfhxI',
    appId: '1:376786311168:android:04a71fa5bdb080315420e5',
    messagingSenderId: '376786311168',
    projectId: 'tutleneck25',
    storageBucket: 'tutleneck25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5zgzqoB0wgnWBUTBD2WMP5eSMa5eQutM',
    appId: '1:376786311168:ios:9c387f3d17d40c965420e5',
    messagingSenderId: '376786311168',
    projectId: 'tutleneck25',
    storageBucket: 'tutleneck25.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5zgzqoB0wgnWBUTBD2WMP5eSMa5eQutM',
    appId: '1:376786311168:ios:9c387f3d17d40c965420e5',
    messagingSenderId: '376786311168',
    projectId: 'tutleneck25',
    storageBucket: 'tutleneck25.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArE-oAEdxp_7eTAY5F5kiCnSBSDUuBTzQ',
    appId: '1:376786311168:web:3b6b997a54866a7c5420e5',
    messagingSenderId: '376786311168',
    projectId: 'tutleneck25',
    authDomain: 'tutleneck25.firebaseapp.com',
    storageBucket: 'tutleneck25.firebasestorage.app',
  );
}
